services:
  dev-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: relity
    networks:
      - kimuna
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - kimuna
    environment:
      - RABBITMQ_DEFAULT_USER=kimuna
      - RABBITMQ_DEFAULT_PASS=1234
networks:
  kimuna:
