-- AlterTable
ALTER TABLE "Member" ALTER COLUMN "pfp" DROP NOT NULL,
ALTER COLUMN "pfp" DROP DEFAULT,
ALTER COLUMN "banner" DROP NOT NULL,
ALTER COLUMN "banner" DROP DEFAULT,
ALTER COLUMN "nickname" DROP NOT NULL,
ALTER COLUMN "nickname" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "banner" TEXT;
